apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: testa
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testa 
  name: testa
spec:
  port:
    targetPort: 8501
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: testa 
    weight: 100 
  wildcardPolicy: None
